In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as  plt

In [84]:
 dataset=pd.read_csv("Book1.csv")

In [85]:
dataset

,Sn NO,User ID,Product ID,Gender,Age,Occupation,City-category,Current_city,Martinal status,Product_category-1,Product_category-2,Product_category-3,Purchase
0,1,1000001,P00069042,F,0-17,10,A,2,0,3,0,0,8370
1,2,1000001,P00248942,F,0-17,10,A,2,0,1,6,14,15200
2,3,1000001,P00087842,F,0-17,10,A,2,0,12,0,0,1422
3,4,1000001,P00085442,F,0-17,10,A,2,0,12,14,0,1057
4,5,1000002,P00285442,M,55+,16,C,4,0,8,0,0,7969
5,6,1000003,P00193542,M,26-35,15,A,3,0,1,2,0,15227
6,7,1000004,P00184942,M,46-50,7,B,2,1,1,8,17,19215
7,8,1000004,P00346142,M,46-50,7,B,2,1,1,15,0,15854
8,9,1000004,P0097242,M,46-50,7,B,2,1,1,16,0,15686
9,10,1000005,P00274942,M,26-35,20,A,1,1,8,0,0,7871
10,11,1000005,P00251242,M,26-35,20,A,1,1,5,11,0,5254
11,12,1000005,P00014542,M,26-35,20,A,1,1,8,0,0,3957
12,13,1000005,P00031342,M,26-35,20,A,1,1,8,0,0,6073
13,14,1000005,P00145042,M,26-35,20,A,1,1,1,2,5,15665
14,15,1000006,P00231342,F,51-55,9,A,1,0,5,8,14,5378
15,16,1000006,P00190242,F,51-55,9,A,1,0,4,5,0,2079
16,17,1000006,P0096642,F,51-55,9,A,1,0,2,3,4,13055
17,18,1000006,P00058442,F,51-55,9,A,1,0,5,14,0,8851
18,19,1000007,P00036842,M,36-45,1,B,1,1,1,14,16,11788
19,20,1000008,P00249542,M,26-35,12,C,4,1,1,5,15,19614
20,21,1000008,P00220442,M,26-35,12,C,4,1,5,14,0,8584
21,22,1000008,P00156442,M,26-35,12,C,4,1,8,0,0,9872
22,23,1000008,P00213742,M,26-35,12,C,4,1,8,0,0,9743
23,24,1000008,P00214442,M,26-35,12,C,4,1,8,0,0,5982
24,25,1000008,P00303442,M,26-35,12,C,4,1,1,8,14,11927
25,26,1000009,P00135742,M,26-35,17,C,0,0,6,8,0,16662
26,27,1000009,P00039942,M,26-35,17,C,0,0,8,0,0,5887
27,28,1000009,P00161442,M,26-35,17,C,0,0,5,14,0,6973
28,29,1000009,P00078742,M,26-35,17,C,0,0,5,8,14,5391
29,30,1000010,P00085942,F,36-45,1,B,4,1,2,4,8,16352
...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,171,1000033,P00351842,M,46-50,3,A,1,1,5,0,0,5265
171,172,1000033,P00145442,M,46-50,3,A,1,1,8,15,0,7888
172,173,1000033,P00344242,M,46-50,3,A,1,1,8,10,0,4035
173,174,1000033,P00327242,M,46-50,3,A,1,1,5,8,0,5280
174,175,1000033,P00241142,M,46-50,3,A,1,1,8,0,0,7909
175,176,1000033,P00219242,M,46-50,3,A,1,1,4,5,0,811
176,177,1000033,P00057342,M,46-50,3,A,1,1,4,5,0,2846
177,178,1000033,P00165742,M,46-50,3,A,1,1,8,16,0,7994
178,179,1000033,P00154642,M,46-50,3,A,1,1,8,0,0,3897
179,180,1000034,P00192942,F,18-25,0,A,0,0,5,0,0,6996
180,181,1000034,P00247042,F,18-25,0,A,0,0,5,14,0,8593
181,182,1000034,P00150542,F,18-25,0,A,0,0,5,0,0,6917
182,183,1000034,P00347142,F,18-25,0,A,0,0,5,0,0,5329
183,184,1000034,P00326742,F,18-25,0,A,0,0,11,0,0,5942
184,185,1000034,P00085942,F,18-25,0,A,0,0,2,4,8,15895
185,186,1000034,P00330442,F,18-25,0,A,0,0,5,14,0,7165
186,187,1000034,P00327842,F,18-25,0,A,0,0,8,16,0,9846
187,188,1000034,P00218342,F,18-25,0,A,0,0,5,0,0,8701
188,189,1000034,P00259042,F,18-25,0,A,0,0,5,0,0,8757
189,190,1000035,P00102542,M,46-50,1,C,4,1,8,0,0,6109
190,191,1000035,P00285442,M,46-50,1,C,4,1,8,0,0,6139
191,192,1000035,P00121142,M,46-50,1,C,4,1,8,0,0,5897
192,193,1000035,P00228242,M,46-50,1,C,4,1,8,0,0,3990
193,194,1000035,P00129542,M,46-50,1,C,4,1,8,14,0,6153
194,195,1000035,P00309542,M,46-50,1,C,4,1,5,14,0,5319
195,196,1000035,P00106742,M,46-50,1,C,4,1,3,5,0,10767
196,197,1000036,P00102642,M,26-35,3,B,0,0,4,8,9,2832
197,198,1000036,P00127442,M,26-35,3,B,0,0,1,2,15,8066
198,199,1000036,P00345642,M,26-35,3,B,0,0,1,15,16,15812
199,200,1000036,P00357842,M,26-35,3,B,0,0,5,0,0,6967

In [74]:
 dataset.isnull().any()

Sn NO                 False
User ID               False
Product ID            False
Gender                False
Age                   False
Occupation            False
City-category         False
Current_city          False
Martinal status       False
Product_category-1    False
Product_category-2    False
Product_category-3    False
Purchase              False
dtype: bool

In [55]:
    x=dataset.iloc[:,1:-1].values
x

array([[1000001, 'P00069042', 'F', ..., 3, 0, 0],
       [1000001, 'P00248942', 'F', ..., 1, 6, 14],
       [1000001, 'P00087842', 'F', ..., 12, 0, 0],
       ...,
       [1000036, 'P00127442', 'M', ..., 1, 2, 15],
       [1000036, 'P00345642', 'M', ..., 1, 15, 16],
       [1000036, 'P00357842', 'M', ..., 5, 0, 0]], dtype=object)

In [56]:
y=dataset.iloc[:,12:].values
y

array([[ 8370],
       [15200],
       [ 1422],
       [ 1057],
       [ 7969],
       [15227],
       [19215],
       [15854],
       [15686],
       [ 7871],
       [ 5254],
       [ 3957],
       [ 6073],
       [15665],
       [ 5378],
       [ 2079],
       [13055],
       [ 8851],
       [11788],
       [19614],
       [ 8584],
       [ 9872],
       [ 9743],
       [ 5982],
       [11927],
       [16662],
       [ 5887],
       [ 6973],
       [ 5391],
       [16352],
       [ 8886],
       [ 5875],
       [ 8854],
       [10946],
       [ 5152],
       [ 7089],
       [12909],
       [ 8770],
       [15212],
       [15705],
       [ 7947],
       [18963],
       [ 8718],
       [16406],
       [12642],
       [10007],
       [11562],
       [ 6171],
       [19327],
       [ 8027],
       [15246],
       [ 6865],
       [ 5839],
       [15912],
       [12107],
       [ 5848],
       [19653],
       [ 5958],
       [11415],
       [ 5380],
       [ 3594],
       [ 4209],
       [ 5407],
       [ 7803],
       [11458],
       [11755],
       [ 8702],
       [15872],
       [ 8609],
       [15172],
       [ 1780],
       [10754],
       [ 2802],
       [19473],
       [19672],
       [19313],
       [15182],
       [15985],
       [16454],
       [13551],
       [  697],
       [ 7030],
       [ 5430],
       [ 8011],
       [ 5912],
       [ 7746],
       [19525],
       [11959],
       [19172],
       [ 8773],
       [11023],
       [ 4654],
       [ 4664],
       [ 8290],
       [ 7011],
       [ 4211],
       [ 1539],
       [ 3055],
       [12099],
       [ 8797],
       [10681],
       [ 7801],
       [15517],
       [12098],
       [ 6976],
       [ 5384],
       [ 6973],
       [ 5168],
       [ 3449],
       [ 7177],
       [ 4570],
       [ 9564],
       [15766],
       [ 8481],
       [ 6108],
       [15354],
       [12015],
       [15371],
       [19239],
       [16137],
       [11887],
       [ 5183],
       [  584],
       [ 7601],
       [ 2230],
       [ 6940],
       [15774],
       [15361],
       [15770],
       [18974],
       [ 1848],
       [ 3624],
       [ 5275],
       [ 5356],
       [ 5411],
       [ 9734],
       [ 7814],
       [ 6098],
       [ 5195],
       [ 5220],
       [16093],
       [ 3702],
       [ 8696],
       [ 7730],
       [ 9836],
       [16500],
       [15903],
       [  758],
       [ 6904],
       [ 8690],
       [ 8624],
       [ 3904],
       [19068],
       [ 7963],
       [15511],
       [11859],
       [ 9735],
       [ 4166],
       [ 6927],
       [ 8596],
       [ 5248],
       [10592],
       [ 3482],
       [ 7134],
       [ 7854],
       [17391],
       [ 6074],
       [ 6119],
       [15333],
       [ 6129],
       [ 5265],
       [ 7888],
       [ 4035],
       [ 5280],
       [ 7909],
       [  811],
       [ 2846],
       [ 7994],
       [ 3897],
       [ 6996],
       [ 8593],
       [ 6917],
       [ 5329],
       [ 5942],
       [15895],
       [ 7165],
       [ 9846],
       [ 8701],
       [ 8757],
       [ 6109],
       [ 6139],
       [ 5897],
       [ 3990],
       [ 6153],
       [ 5319],
       [10767],
       [ 2832],
       [ 8066],
       [15812],
       [ 6967]], dtype=int64)

In [57]:
 from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [58]:
 x[:,1]=lb.fit_transform(x[:,1])
x

array([[1000001, 30, 'F', ..., 3, 0, 0],
       [1000001, 125, 'F', ..., 1, 6, 14],
       [1000001, 38, 'F', ..., 12, 0, 0],
       ...,
       [1000036, 64, 'M', ..., 1, 2, 15],
       [1000036, 174, 'M', ..., 1, 15, 16],
       [1000036, 183, 'M', ..., 5, 0, 0]], dtype=object)

In [59]:
 x[:,2]=lb.fit_transform(x[:,2])
x

array([[1000001, 30, 0, ..., 3, 0, 0],
       [1000001, 125, 0, ..., 1, 6, 14],
       [1000001, 38, 0, ..., 12, 0, 0],
       ...,
       [1000036, 64, 1, ..., 1, 2, 15],
       [1000036, 174, 1, ..., 1, 15, 16],
       [1000036, 183, 1, ..., 5, 0, 0]], dtype=object)

In [60]:
 x[:,3]=lb.fit_transform(x[:,3])
x

array([[1000001, 30, 0, ..., 3, 0, 0],
       [1000001, 125, 0, ..., 1, 6, 14],
       [1000001, 38, 0, ..., 12, 0, 0],
       ...,
       [1000036, 64, 1, ..., 1, 2, 15],
       [1000036, 174, 1, ..., 1, 15, 16],
       [1000036, 183, 1, ..., 5, 0, 0]], dtype=object)

In [61]:
 x[:,5]=lb.fit_transform(x[:,5])
x

array([[1000001, 30, 0, ..., 3, 0, 0],
       [1000001, 125, 0, ..., 1, 6, 14],
       [1000001, 38, 0, ..., 12, 0, 0],
       ...,
       [1000036, 64, 1, ..., 1, 2, 15],
       [1000036, 174, 1, ..., 1, 15, 16],
       [1000036, 183, 1, ..., 5, 0, 0]], dtype=object)

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state= 0)

In [63]:
 x_test

array([[1000007, 16, 1, 3, 1, 1, 1, 1, 1, 14, 16],
       [1000033, 182, 1, 4, 3, 0, 1, 1, 5, 0, 0],
       [1000022, 158, 1, 1, 15, 0, 4, 0, 5, 14, 0],
       [1000022, 181, 1, 1, 15, 0, 4, 0, 1, 8, 17],
       [1000033, 84, 1, 4, 3, 0, 1, 1, 8, 16, 0],
       [1000034, 178, 0, 1, 0, 0, 0, 0, 5, 0, 0],
       [1000003, 98, 1, 2, 15, 0, 3, 0, 1, 2, 0],
       [1000027, 54, 1, 2, 11, 2, 1, 1, 2, 17, 0],
       [1000005, 10, 1, 2, 20, 0, 1, 1, 8, 0, 0],
       [1000029, 119, 1, 3, 7, 2, 1, 0, 1, 15, 0],
       [1000015, 85, 1, 2, 7, 0, 1, 0, 8, 0, 0],
       [1000024, 101, 0, 2, 7, 0, 3, 1, 5, 8, 0],
       [1000034, 123, 0, 1, 0, 0, 0, 0, 5, 14, 0],
       [1000029, 180, 1, 3, 7, 2, 1, 0, 1, 5, 0],
       [1000018, 186, 0, 1, 3, 1, 3, 0, 4, 5, 0],
       [1000004, 176, 1, 4, 7, 1, 2, 1, 1, 15, 0],
       [1000010, 27, 0, 3, 1, 1, 4, 1, 3, 4, 0],
       [1000026, 20, 1, 2, 7, 1, 2, 1, 5, 0, 0],
       [1000010, 91, 0, 3, 1, 1, 4, 1, 5, 12, 0],
       [1000018, 57, 0, 1, 3, 1, 3, 0, 1, 2, 0],
       [1000034, 162, 0, 1, 0, 0, 0, 0, 11, 0, 0],
       [1000027, 53, 1, 2, 11, 2, 1, 1, 2, 0, 0],
       [1000010, 157, 0, 3, 1, 1, 4, 1, 8, 0, 0],
       [1000031, 55, 1, 6, 7, 2, 2, 0, 5, 14, 0],
       [1000015, 169, 1, 2, 7, 0, 1, 0, 5, 8, 0],
       [1000023, 11, 1, 3, 0, 1, 3, 1, 1, 5, 12],
       [1000034, 97, 0, 1, 0, 0, 0, 0, 5, 0, 0],
       [1000034, 166, 0, 1, 0, 0, 0, 0, 5, 14, 0],
       [1000023, 48, 1, 3, 0, 1, 3, 1, 13, 16, 0],
       [1000010, 74, 0, 3, 1, 1, 4, 1, 6, 10, 13],
       [1000006, 188, 0, 5, 9, 0, 1, 0, 2, 3, 4],
       [1000014, 143, 1, 3, 0, 2, 0, 0, 8, 11, 0],
       [1000028, 87, 0, 2, 1, 2, 2, 1, 5, 8, 0],
       [1000022, 116, 1, 1, 15, 0, 4, 0, 2, 4, 15],
       [1000008, 104, 1, 2, 12, 2, 4, 1, 8, 0, 0],
       [1000035, 41, 1, 4, 1, 2, 4, 1, 8, 0, 0],
       [1000025, 59, 1, 1, 4, 2, 4, 0, 1, 2, 0],
       [1000002, 148, 1, 6, 16, 2, 4, 0, 8, 0, 0],
       [1000018, 80, 0, 1, 3, 1, 3, 0, 8, 14, 0],
       [1000022, 6, 1, 1, 15, 0, 4, 0, 5, 0, 0]], dtype=object)

In [64]:
 dataset.corr()

,Sn NO,User ID,Occupation,Current_city,Martinal status,Product_category-1,Product_category-2,Product_category-3,Purchase
Sn NO,1.000000,0.994459,-0.344006,-0.220720,0.066698,0.121678,0.012040,-0.136731,-0.194392
User ID,0.994459,1.000000,-0.345723,-0.220376,0.046652,0.110074,0.012760,-0.133120,-0.184043
Occupation,-0.344006,-0.345723,1.000000,0.037606,-0.280637,0.009467,-0.079200,-0.081930,-0.076750
Current_city,-0.220720,-0.220376,0.037606,1.000000,0.185550,-0.050096,-0.120206,0.097375,0.109402
Martinal status,0.066698,0.046652,-0.280637,0.185550,1.000000,0.113364,0.007420,-0.024553,-0.012390
Product_category-1,0.121678,0.110074,0.009467,-0.050096,0.113364,1.000000,-0.061337,-0.512621,-0.636834
Product_category-2,0.012040,0.012760,-0.079200,-0.120206,0.007420,-0.061337,1.000000,0.013384,0.018173
Product_category-3,-0.136731,-0.133120,-0.081930,0.097375,-0.024553,-0.512621,0.013384,1.000000,0.420647
Purchase,-0.194392,-0.184043,-0.076750,0.109402,-0.012390,-0.636834,0.018173,0.420647,1.000000

In [77]:
 from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(x_train,y_train)

F:\New folder\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [78]:
 y_pred=regressor.predict(x_test)

In [79]:
y_pred

array([15665.6,  4925. ,  6499.9, 14562.5,  5781.9,  6689.7, 12879.2,
        8790.9,  4566.6, 12062.1,  6283.4,  6312.3,  8416.5, 14969.5,
        1921.8, 14900.4,  8475. ,  4468.7,  8393.6, 15544. ,  5459.3,
        8449.3,  5805.8,  6707.9,  5732.1, 13313.7,  6987.1,  7693.2,
        4066.5,  8506.1, 16356. , 10135.3,  6949.8, 13754.8,  6489.7,
        9777.8, 13865.6,  5978.7,  6442.6,  5392.7])

In [82]:
y_test

array([[11788],
       [ 5265],
       [ 5168],
       [12099],
       [ 7994],
       [ 5329],
       [15227],
       [15903],
       [ 6073],
       [19068],
       [ 4209],
       [ 6940],
       [ 8593],
       [15511],
       [  697],
       [15854],
       [10946],
       [ 1848],
       [ 8770],
       [19672],
       [ 5942],
       [16500],
       [10007],
       [ 8596],
       [ 3594],
       [ 7601],
       [ 6996],
       [ 7165],
       [  584],
       [12642],
       [13055],
       [ 5848],
       [ 8624],
       [ 9564],
       [ 9743],
       [ 6109],
       [18974],
       [ 7969],
       [ 8011],
       [ 6973]], dtype=int64)

In [83]:
y_predict= regressor.predict([[19, 1000007, 16, 1, 3, 1, 1, 1, 1, 14, 16]])
y_predict

array([17448.5])